update docs for chibaclonk_81337-3
vulcanize/chiba-clonk pull request #57
Opened 2022-08-03 17:52 UTC by sjors-lemniscap

Closes: #XXX

## Description

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

2022-08-04 10:23 UTC, gsk967 requested changes

2022-08-04 10:23 UTC, gsk967 commented on testnet/genesis-validators.md
> +chibaclonkd init <your-node-moniker> --chain-id chibaclonk_81337-3
Please create two sections 
1. fresh initialisation without previous setup 
2. overwrite initialisation from previous setup

2022-08-04 17:09 UTC, sjors-lemniscap commented on testnet/genesis-validators.md
> +chibaclonkd init <your-node-moniker> --chain-id chibaclonk_81337-3
Updated - please review again.

2022-08-05 04:57 UTC, gsk967 approved these changes

2022-08-05 05:13 UTC, merged